### ISSUE TITLE
deepinsight/insightface这个库和你这个InspireFace是什么关系？

### ISSUE THREAD

**Issue by 1xiaowa** [HyperInspire/InspireFace#105]
deepinsight/insightface这个库和你这个InspireFace是什么关系？
insightface是python版本的吗？InspireFace是C++版本的吗？
对于人脸识别的精度是否是一样的？只是语音不一样而已？

**Comment by tunmx** [comment]
该仓库作是insightface的一个product的develop仓库，主要侧重产品落地SDK集成 ，stable地址: [https://github.com/deepinsight/insightface/tree/master/cpp-package/inspireface](https://github.com/deepinsight/insightface/tree/master/cpp-package/inspireface)
