### ISSUE TITLE
在jetson orin nano的arm版上运行输出的人脸质量数qualityConfidence（）和在x86上运行的差距这么大？

### ISSUE THREAD

**Issue by 1xiaowa** [HyperInspire/InspireFace#107]
HFFaceQualityDetect(m_session, multipleFaceData.tokens[i], &qualityConfidence) == 0
qDebug()<<"人脸清晰度"<<qualityConfidence;
在arm上运行输出的值几乎都是-1.92984e+07
在x86上运行输出的值是0~1。
为什么？我没改代码。

**Comment by tunmx** [comment]
是不是这个模型没推理成功？ 有更多信息吗

**Comment by 1xiaowa** [comment]
没有其他输出信息，有时运行时，qualityConfidence输出-1.30252e+36左右。重新运行-2.25187e+14左右。重新运行-3.778e+21左右毫无规律可言。

**Comment by tunmx** [comment]
除了jetson orin nano 您那边还有其他的arm板子可以测试吗？我们在RK的板子上跑过一些 没有遇到这个问题
