### ISSUE TITLE
【Apple silicon】构建产物能否增加 macos aarch64 架构

### ISSUE THREAD

**Issue by idootop** [HyperInspire/InspireFace#108]
如题，想要在 mac M1 芯片的设备上跑起来，谢谢。

**Comment by tunmx** [comment]
工程本身支持Apple Silicon，使用mac编译即可

**Comment by idootop** [comment]
了解，多谢回复。

另外，来这边是想看看有没有预构建的产物，方便直接体验效果。

自己从头搭建编译环境构建起来比较麻烦，遂放弃~ 

我想如果能有更多平台的预编译产物，应该能帮助更多像我一样的人，快速上手使用这个项目。

**Comment by tunmx** [comment]
实际上我们每次提交release时都会在github actions上添加需要编译和测试的平台[Github Actions](https://github.com/HyperInspire/InspireFace/actions/runs/11251054378)，我们可能会在下个版本添加M系列的mac相关的预编译库

**Comment by idootop** [comment]
那真是太好了，非常感谢。

本人对 C/C++ 构建环境不是很熟，但又非常想使用这个项目。

实际上我也是在你们的 Github CI 下面没有找到 macOS 环境相关的构建脚本，才提的这个 issue。

如果有相关 CI 脚本的话，那我就可以直接 fork 一份在 Github Action 上自行构建了。
