### ISSUE TITLE
After calling the HFExecuteFaceTrack method, detectedNum outputs 1 but the PHFFaceBasicToken is empty

### ISSUE THREAD

**Issue by lwh504530121** [HyperInspire/InspireFace#110]
Hello, after calling HFExecuteFaceTrack method, detectedNum output is 1, confidence and Angle are normal output, but PHFFaceBasicToken is empty, what is the problem

**Comment by lwh504530121** [comment]
My environment is android arm64, and I still had the same problem when testing both the 1.1.7 and 1.1.6 version libraries.

**Comment by tunmx** [comment]
Can you show me your code snippet? This will make it easier for me to spot problems.
