### ISSUE TITLE
ios 这个方法失败： HFExecuteFaceTrack(session, imageHandle, &multipleFaceData); （ Execute HFExecuteFaceTrack error）

### ISSUE THREAD

**Issue by zhengdian01** [HyperInspire/InspireFace#130]
-(HResult)detectFaceWithCVPixelBuffer:(CGImageRef)img {

    // Load a image
    HFImageBitmap image;
    HResult ret = HFCreateImageBitmapFromFilePath([[NSBundle mainBundle] pathForResource:@"multi-face.png" ofType:nil].UTF8String, 3, &image);

    if (ret != HSUCCEED) {
        NSLog(@"The source entered is not a picture or read error.\n");
        return ret;
    }
    
    // Prepare an image parameter structure for configuration
    HFImageStream imageHandle = {0};
    ret = HFCreateImageStreamFromImageBitmap(image, HF_CAMERA_ROTATION_0, &imageHandle);
    if (ret != HSUCCEED) {
        NSLog(@"Create ImageStream error: ");
        return ret;
    }

    // Execute HF_FaceContextRunFaceTrack captures face information in an image
    HFMultipleFaceData multipleFaceData = {0};
    ret = HFExecuteFaceTrack(session, imageHandle, &multipleFaceData);
    if (ret != HSUCCEED) {
        NSLog(@"Execute HFExecuteFaceTrack error\n");
        return ret;
    }
    // Print the number of faces detected
    NSInteger faceNum = multipleFaceData.detectedNum;
    NSLog(@"Num of face: %ld\n", faceNum);

    // The memory must be freed at the end of the program
    ret = HFReleaseImageBitmap(image);
    if (ret != HSUCCEED) {
        NSLog(@"Release image bitmap error: %lu\n", ret);
        return ret;
    }

    ret = HFReleaseImageStream(imageHandle);
    if (ret != HSUCCEED) {
        NSLog(@"Release image stream error: %lu\n", ret);
        return ret;
    }
    
    return ret;
}

**Comment by tunmx** [comment]
resolved
