### ISSUE TITLE
请问可不可以出一个Android端的demo

### ISSUE THREAD

**Issue by Caleb-Rainbow** [HyperInspire/InspireFace#66]
在Android端导入试了，加载pack没有问题，在HFCreateInspireFaceSessionOptional这一步就会闪退，希望能出一个Android端的教程或demo参考一下。
使用的ndk版本： 26.1.10909125
测试架构：arm64-v8a
系统版本：Android13.0
opencv-android：4.10.0
这是我的代码片段
![image](https://github.com/HyperInspire/InspireFace/assets/56993378/fb86166c-6742-46fe-ad13-043a2065857b)
这是日志输出情况
![image](https://github.com/HyperInspire/InspireFace/assets/56993378/37b40c3e-a764-4bce-953d-4a24503bdffe)

**Comment by tunmx** [comment]
你好，安卓demo已经在计划中，很快就会提交

**Comment by wenjianhui1** [comment]
你好Androiddemo  我也需要麻烦了

**Comment by tunmx** [comment]
安卓端的demo第一版本已经更新，更多演示功能会持续集成

**Comment by tunmx** [comment]
#117
