### ISSUE TITLE
The previously registered person cannot be found after the program restarts

### ISSUE THREAD

**Issue by 1xiaowa** [HyperInspire/InspireFace#93]
constructor：
![1](https://github.com/user-attachments/assets/a5ac4a5d-84a6-47d7-9524-e7413a78b979)
recognition：
 
![image](https://github.com/user-attachments/assets/6ca7d922-6700-41c7-a3eb-071dc95daea6)
![image](https://github.com/user-attachments/assets/01864011-07b1-4862-b707-92f8be28f54b)

**Comment by tunmx** [comment]
Can you share the version info you are using? Have you pulled the latest code from the repository?

**Comment by 1xiaowa** [comment]
版本是1.1.5，是不是最新版没有这个问题？还是我使用方式不对？

**Comment by tunmx** [comment]
你试一下最新版的，这个读不到数据库应该是一个bug，前面修复了 还没有release版本
