### ISSUE TITLE
 how to make model package files

### ISSUE THREAD

**Issue by zjruiting** [HyperInspire/InspireFace#94]
是否可以出一个说明，完整描述下模型包的生成步骤，可以满足通过自己训练并打包生成的要求。如果已有指导的话哪里可以获取介绍。

**Comment by tunmx** [comment]
你好，该项目隶属于[insightface](https://insightface.ai/)，项目中所使用的大部分主要的算法和模型如人脸识别、人脸检测和人脸对齐等均可以在insightface仓库中找到对应的训练代码；打包方法和参考源代码中的模型加载部分和tools文件夹中的打包工具
